version: 2

formats: [pdf, epub]
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    create_environment:
      - echo "Preparing environment"
    install:
      - echo "Installing dependencies"
    build:
      html:
        - echo "Building HTML"
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - echo "MediaXR" > $READTHEDOCS_OUTPUT/html/index.html
      pdf:
        - echo "Building PDF"
        - mkdir -p $READTHEDOCS_OUTPUT/pdf/
        - echo "MediaXR" > $READTHEDOCS_OUTPUT/pdf/index.pdf
      epub:
        - echo "Building ePub"
        - mkdir -p $READTHEDOCS_OUTPUT/epub/
        - echo "MediaXR" > $READTHEDOCS_OUTPUT/epub/index.epub
