version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
    nodejs: "19"
    rust: "1.64"
    golang: "1.19"

  jobs:
    post_checkout:
      - git fetch --unshallow || true
      - git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*' || true
      - git fetch --all --tags || true

mkdocs:
  
  configuration: mkdocs.yml
