version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    install:
      - pip install pelican
    build:
      html:
        - pelican --settings docs/pelicanconf.py --output $READTHEDOCS_OUTPUT/html/ docs/
